
package othello;

import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class ChooseAvatarFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChooseAvatarFrame
     */
    public ChooseAvatarFrame() {
        
        initComponents();
        buttonGroup1.add(Blossom1);
        buttonGroup1.add(Buttercup1);
        buttonGroup1.add(Bubbles1);
        buttonGroup1.add(None1);
        buttonGroup2.add(Blossom2);
        buttonGroup2.add(Buttercup2);
        buttonGroup2.add(Bubbles2);
        buttonGroup2.add(None2);
        
        Player1Label.setText(othello.txtPlayerOne.getText());
        Player2Label.setText(othello.txtPlayerTwo.getText());
        
        Player1IconLabel.setText(othello.txtPlayerOne.getText());
        Player2IconLabel.setText(othello.txtPlayerTwo.getText());
        
        if (othello.player1Avatar.equals("Blossom.png"))
        {
            Blossom1.setSelected(true);
             ImageIcon icon = new ImageIcon(getClass().getResource("Blossom.png"));
        //icon.getImage().flush();
            Player1IconLabel.setIcon( icon );
        }
    else if (othello.player1Avatar.equals("Buttercup.jpg"))
        {
            Buttercup1.setSelected(true);
             ImageIcon icon = new ImageIcon(getClass().getResource("Buttercup.jpg"));
        //icon.getImage().flush();
            Player1IconLabel.setIcon( icon );
        }
    else if (othello.player1Avatar.equals("Bubbles.gif"))
        {
            Bubbles1.setSelected(true);
            ImageIcon icon = new ImageIcon(getClass().getResource("Bubbles.gif"));
        //icon.getImage().flush();
            Player1IconLabel.setIcon( icon );
        }
    else if (othello.player1Avatar.equals("default.png"))
    {
         None1.setSelected(true); 
         ImageIcon icon = new ImageIcon(getClass().getResource("default.png"));
        //icon.getImage().flush();
            Player1IconLabel.setIcon( icon );
    }
    
      if (othello.player2Avatar.equals("Blossom.png"))
        {
            Blossom2.setSelected(true);
             ImageIcon icon = new ImageIcon(getClass().getResource("Blossom.png"));
        //icon.getImage().flush();
            Player2IconLabel.setIcon( icon );
        }
    else if (othello.player2Avatar.equals("Buttercup.jpg"))
        {
            Buttercup2.setSelected(true);
            ImageIcon icon = new ImageIcon(getClass().getResource("Buttercup.jpg"));
        //icon.getImage().flush();
            Player2IconLabel.setIcon( icon );

        }
    else if (othello.player2Avatar.equals("Bubbles.gif"))
        {
            Bubbles2.setSelected(true);
  ImageIcon icon = new ImageIcon(getClass().getResource("Bubbles.gif"));
        //icon.getImage().flush();
            Player2IconLabel.setIcon( icon );
        }
    else if (othello.player2Avatar.equals("default.png"))
        {
          None2.setSelected(true);
          ImageIcon icon = new ImageIcon(getClass().getResource("default.png"));
        //icon.getImage().flush();
            Player2IconLabel.setIcon( icon );
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Player1Label = new javax.swing.JLabel();
        Player2Label = new javax.swing.JLabel();
        Blossom1 = new javax.swing.JRadioButton();
        Buttercup1 = new javax.swing.JRadioButton();
        Bubbles1 = new javax.swing.JRadioButton();
        Blossom2 = new javax.swing.JRadioButton();
        Buttercup2 = new javax.swing.JRadioButton();
        Bubbles2 = new javax.swing.JRadioButton();
        Player1IconLabel = new javax.swing.JLabel();
        Player2IconLabel = new javax.swing.JLabel();
        None1 = new javax.swing.JRadioButton();
        None2 = new javax.swing.JRadioButton();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 241, 221));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setResizable(false);

        Player1Label.setText("Player 1 choose you're avatar");

        Player2Label.setText("Player 2 choose you're avatar");

        Blossom1.setText("Blossom");
        Blossom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blossom1ActionPerformed(evt);
            }
        });

        Buttercup1.setText("Buttercup");
        Buttercup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttercup1ActionPerformed(evt);
            }
        });

        Bubbles1.setText("Bubbles");
        Bubbles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bubbles1ActionPerformed(evt);
            }
        });

        Blossom2.setText("Blossom");
        Blossom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blossom2ActionPerformed(evt);
            }
        });

        Buttercup2.setText("Buttercup");
        Buttercup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttercup2ActionPerformed(evt);
            }
        });

        Bubbles2.setText("Bubbles");
        Bubbles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bubbles2ActionPerformed(evt);
            }
        });

        Player1IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/othello/default.png"))); // NOI18N
        Player1IconLabel.setText("Player1");

        Player2IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/othello/default.png"))); // NOI18N
        Player2IconLabel.setText("Player2");

        None1.setText("None");
        None1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                None1ActionPerformed(evt);
            }
        });

        None2.setText("None");
        None2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                None2ActionPerformed(evt);
            }
        });

        SaveButton.setText("Save Changes");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Player1IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(Player2IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(None2)
                    .addComponent(Bubbles2)
                    .addComponent(Buttercup2)
                    .addComponent(Bubbles1)
                    .addComponent(Buttercup1)
                    .addComponent(Blossom1)
                    .addComponent(Blossom2)
                    .addComponent(None1))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Blossom1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buttercup1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bubbles1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(None1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Player1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player1IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Player2Label)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Player2IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Blossom2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buttercup2)
                        .addGap(34, 34, 34)
                        .addComponent(Bubbles2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(None2)
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Blossom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blossom1ActionPerformed

        ImageIcon icon = new ImageIcon(getClass().getResource("Blossom.png"));
        //icon.getImage().flush();
        Player1IconLabel.setIcon( icon );
        // TODO add your handling code here:
    }//GEN-LAST:event_Blossom1ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
    if (Blossom1.isSelected())
        {
            othello.player1Avatar = "Blossom.png";
           
        }
    else if (Buttercup1.isSelected())
        {
            othello.player1Avatar = "Buttercup.jpg";
           
        }
    else if (Bubbles1.isSelected())
        {
            othello.player1Avatar = "Bubbles.gif";
            
        }
    else if (None1.isSelected())
    {
          othello.player1Avatar = "default.png"; 
          
    }
    
      if (Blossom2.isSelected())
        {
            othello.player2Avatar = "Blossom.png";
           
        }
    else if (Buttercup2.isSelected())
        {
            othello.player2Avatar = "Buttercup.jpg";
            
        }
    else if (Bubbles2.isSelected())
        {
            othello.player2Avatar = "Bubbles.gif";
          
        }
    else if (None2.isSelected())
        {
          othello.player2Avatar = "default.png"; 
          
        }
    ///othello.player1IconLabel.setText(othello.player1Avatar);
    //othello.player2IconLabel.setText(othello.player2Avatar);
    othello.player1IconLabel.setText(othello.txtPlayerOne.getText());
    othello.player2IconLabel.setText(othello.txtPlayerTwo.getText()); 
    ImageIcon icon1 = new ImageIcon(getClass().getResource(othello.player1Avatar));
    othello.player1IconLabel.setIcon( icon1 );
    ImageIcon icon2 = new ImageIcon(getClass().getResource(othello.player2Avatar));
    othello.player2IconLabel.setIcon( icon2 );
    //othello.player1IconLabel.setText("");
    //othello.player2IconLabel.setText("");
    repaint();
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void None1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_None1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("default.png"));
        //icon.getImage().flush();
        Player1IconLabel.setIcon( icon );
    }//GEN-LAST:event_None1ActionPerformed

    private void Buttercup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttercup1ActionPerformed
     ImageIcon icon = new ImageIcon(getClass().getResource("Buttercup.jpg"));
        //icon.getImage().flush();
        Player1IconLabel.setIcon( icon );   // TODO add your handling code here:
    }//GEN-LAST:event_Buttercup1ActionPerformed

    private void Bubbles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bubbles1ActionPerformed
      ImageIcon icon = new ImageIcon(getClass().getResource("Bubbles.gif"));
        //icon.getImage().flush();
        Player1IconLabel.setIcon( icon );  // TODO add your handling code here:
    }//GEN-LAST:event_Bubbles1ActionPerformed

    private void Buttercup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttercup2ActionPerformed
    ImageIcon icon = new ImageIcon(getClass().getResource("Buttercup.jpg"));
        //icon.getImage().flush();
        Player2IconLabel.setIcon( icon );    // TODO add your handling code here:
    }//GEN-LAST:event_Buttercup2ActionPerformed

    private void Blossom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blossom2ActionPerformed
ImageIcon icon = new ImageIcon(getClass().getResource("Blossom.png"));
        //icon.getImage().flush();
        Player2IconLabel.setIcon( icon );        // TODO add your handling code here:
    }//GEN-LAST:event_Blossom2ActionPerformed

    private void Bubbles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bubbles2ActionPerformed
    ImageIcon icon = new ImageIcon(getClass().getResource("Bubbles.gif"));
        //icon.getImage().flush();
        Player2IconLabel.setIcon( icon );    // TODO add your handling code here:
    }//GEN-LAST:event_Bubbles2ActionPerformed

    private void None2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_None2ActionPerformed
     ImageIcon icon = new ImageIcon(getClass().getResource("default.png"));
        //icon.getImage().flush();
        Player2IconLabel.setIcon( icon );   // TODO add your handling code here:
    }//GEN-LAST:event_None2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseAvatarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseAvatarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseAvatarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseAvatarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseAvatarFrame().setVisible(true);
            }
        });
    }

    //private javax.swing.JLabel Image1;
    //private javax.swing.JLabel Image2;
    String imageBlossom = "/othello/Blossom.png";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Blossom1;
    private javax.swing.JRadioButton Blossom2;
    private javax.swing.JRadioButton Bubbles1;
    private javax.swing.JRadioButton Bubbles2;
    private javax.swing.JRadioButton Buttercup1;
    private javax.swing.JRadioButton Buttercup2;
    private javax.swing.JRadioButton None1;
    private javax.swing.JRadioButton None2;
    private javax.swing.JLabel Player1IconLabel;
    private javax.swing.JLabel Player1Label;
    private javax.swing.JLabel Player2IconLabel;
    private javax.swing.JLabel Player2Label;
    private javax.swing.JButton SaveButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
